image: archlinux
packages: 
  - nodejs
  - npm
  - s3cmd
sources:
  - https://git.sr.ht/~hermiod/website
secrets:
  - fd6d743a-04f7-4845-8c0c-67a9a6170c19
tasks:
  - build: |
      npx @11ty/eleventy
      s3cmd put _site/* s3://hermiod-website --recursive
      s3cmd setacl s3://hermiod-website --acl-public --recursive
