image: archlinux
packages: 
  - nodejs
  - npm
  - s3cmd
sources:
  - https://git.sr.ht/~hermiod/website
secrets:
  - bb092798-abe0-44d1-b364-2e3f4e71595f
tasks:
  - build: |
      npx @11ty/eleventy
      ./cloudflare_secrets.sh
      npx wrangler pages publish dist --project-name=hermiod-com
